In [1]:
import json

In [2]:
data = json.load(open('/data2/polyakov/instruction_tuning/ToolBench/data/toolbench_multistep_dataset_g_query_format_100.json', 'r'))

In [7]:
data[0]['api_list']

[{'category_name': 'Health_and_Fitness',
  'tool_name': 'body_mass_index_bmi_calculator',
  'api_name': 'metric_kilograms',
  'api_description': 'This endpoint will calculate the BMI of an individual using the imperial measurement system.',
  'required_parameters': [{'name': 'weight',
    'type': 'NUMBER',
    'description': 'The weight of someone in kilograms (kgs)',
    'default': '150'},
   {'name': 'height',
    'type': 'NUMBER',
    'description': 'The height of someone in meters (m)',
    'default': '1.83'}],
  'optional_parameters': [],
  'method': 'GET'},
 {'category_name': 'Health_and_Fitness',
  'tool_name': 'body_mass_index_bmi_calculator',
  'api_name': 'weight_category',
  'api_description': 'Retrieve the weight category of an individual based on their BMI',
  'required_parameters': [{'name': 'bmi',
    'type': 'NUMBER',
    'description': '',
    'default': '19.2'}],
  'optional_parameters': [],
  'method': 'GET'}]

In [10]:
all_apis = set()
for item in data:
    for api in item['api_list']:
        if api['tool_name'] in {'great_circle_math_api', 'numbers', 'watch_database'}:
            print(api)
        all_apis.add(api['tool_name'])

{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Education', 'tool_name': 'numbers', 'api_name': 'get_date_fact', 'api_description': 'Get a fact about a day of year', 'required_parameters': [{'name': 'month', 'type': 'STRING', 'description': 'The 1-indexed month (eg. 6 for June)', 'default': '6'}, {'name': 'day', 'type': 'STRING', 'description': 'The day of the month', 'default': '21'}], 'optional_parameters': [{'name': 'fragment', 'type': 'STRING', 'description': 'Add "?fragment=true" to return the fact as a sentence fragment that can be easily included as part of a larger sentence. This means that the first word is lowercase and ending punctuation is omitted. For trivia and math, a noun phrase is returned that can be used in a sentence like “We now have more users than [fact as fragment]!”.', 'default': True}, {'name': 'json', 'type': 'STRING', 'description': 'Specify "true" to return result as JSON instead of plaintext.', 'default': True}], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Travel', 'tool_name': 'great_circle_math_api', 'api_name': 'get_distance_by_city_state_country', 'api_description': 'Takes city, state, and country of both locations and returns latitude, longitude, and calculated miles.', 'required_parameters': [{'name': 'country1', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'country2', 'type': 'string', 'description': '', 'default': 'us'}, {'name': 'state2', 'type': 'string', 'description': '', 'default': 'ca'}, {'name': 'city2', 'type': 'string', 'description': '', 'default': 'sacramento'}, {'name': 'city1', 'type': 'string', 'description': '', 'default': 'birmingham'}, {'name': 'state1', 'type': 'string', 'description': '', 'default': 'al'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_watches_by_brand_family_model', 'api_description': 'Get Watches By Brand Family Model', 'required_parameters': [{'name': 'brandName', 'type': 'string', 'description': '', 'default': 'Omega'}, {'name': 'model', 'type': 'string', 'description': '', 'default': '2005.75.00'}, {'name': 'family', 'type': 'string', 'description': '', 'default': 'Aqua Terra'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_media_links', 'api_description': 'Get Media Links', 'required_parameters': [{'name': 'watchId', 'type': 'ENUM', 'description': '', 'default': ''}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_watches_by_brand_family_model', 'api_description': 'Get Watches By Brand Family Model', 'required_parameters': [{'name': 'brandName', 'type': 'string', 'description': '', 'default': 'Omega'}, {'name': 'model', 'type': 'string', 'description': '', 'default': '2005.75.00'}, {'name': 'family', 'type': 'string', 'description': '', 'default': 'Aqua Terra'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_media_links', 'api_description': 'Get Media Links', 'required_parameters': [{'name': 'watchId', 'type': 'ENUM', 'description': '', 'default': ''}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_watches_by_brand_family_model', 'api_description': 'Get Watches By Brand Family Model', 'required_parameters': [{'name': 'brandName', 'type': 'string', 'description': '', 'default': 'Omega'}, {'name': 'model', 'type': 'string', 'description': '', 'default': '2005.75.00'}, {'name': 'family', 'type': 'string', 'description': '', 'default': 'Aqua Terra'}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_media_links', 'api_description': 'Get Media Links', 'required_parameters': [{'name': 'watchId', 'type': 'ENUM', 'description': '', 'default': ''}], 'optional_parameters': [], 'method': 'GET'}
{'category_name': 'Database', 'tool_name': 'watch_database', 'api_name': 'get_watches_by_brand_family_model', 'api_description': 'Get Watches By Brand Family Model', 'required_parameters': [{'name': 'brandName', 'type': 'string', 'description': '', 'default': 'Omega'}, {'name': 'model', 'type': 'string', 'description': '', 'default': '2005.75.00'}, {'name': 'family', 'type': 'string', 'description': '', 'default': 'Aqua Terra'}], 'optional_parameters': [], 'method': 'GET'}

In [9]:
all_apis

{'Convexity',
 'Measurement Units Converter',
 'body_mass_index_bmi_calculator',
 'celebrity_by_api_ninjas',
 'deezer',
 'great_circle_math_api',
 'numbers',
 'watch_database'}

In [1]:
import json

In [4]:
train_data = json.load(open('/data4/polyakov/instruction_tuning/ToolBench/data/toolllama_G123_dfs_train.json', 'r'))

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [5]:
g2_cat = json.load(open('/data4/polyakov/instruction_tuning/ToolBench/data/test_data_merged/G2_cat.json', 'r'))

In [8]:
g2_cat[0].keys()

dict_keys(['api_list', 'query', 'relevant APIs', 'query_id'])

In [15]:
import pandas as pd

In [16]:
data = pd.read_csv('/data4/polyakov/instruction_tuning/ToolBench/data/answer/test_toollama_2_G3_inst_test_converted/toollama_2/G3_instruction_toollama_2.csv',
                   sep='\t')

In [17]:
data_passed = data[data['pass_rate_label'] == 'passed']

In [26]:
data_solved = data[data['is_solved'] == 'AnswerStatus.Solved']
print(data_solved.shape)
data_solved

(8, 11)

,query,solvable,available_tools,model_intermediate_steps,model_final_step,model,query_id,is_solved,pass_rate_label,reason,not_hallucinate
18,I'm planning a solo trip to Tokyo and would li...,TaskStatus.Solvable,['getlargestcities_for_reverse_geocoding_and_g...,Step 1: {'name': 'getnearestcities_for_reverse...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,5980,AnswerStatus.Solved,passed,"Is solved: The answer provides the names, popu...",True
24,I want to surprise my friend who loves cats wi...,TaskStatus.Solvable,"['kitten_for_placekitten', 'facts_for_cat_fact...",Step 1: {'name': 'kitten_for_kitten_placeholde...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4875,AnswerStatus.Solved,passed,Is solved: The answer is a positive response t...,True
25,I'm preparing a presentation on famous events ...,TaskStatus.Solvable,"['v1_trivia_for_trivia_by_api_ninjas', 'getgam...","Step 1: {'name': 'get_year_fact_for_numbers', ...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6436,AnswerStatus.Solved,passed,Is solved: All the tools in the chain were suc...,True
38,I'm a software developer working on a project ...,TaskStatus.Solvable,['proxies_example_json_for_proxy_spider_proxie...,"Step 1: {'name': 'ip2proxy_api_for_ip2proxy', ...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6773,AnswerStatus.Solved,passed,Is solved: The answer provides all the request...,True
42,I'm writing a book about the power of Bible ve...,TaskStatus.Solvable,"['getverses_for_holy_bible', 'getverseofachapt...",Step 1: {'name': 'getverseofachapter_for_holy_...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,569,AnswerStatus.Solved,passed,Is solved: The answer provides the requested B...,True
44,My family and I are planning a ski trip to Asp...,TaskStatus.Solvable,['gridpoints_wfo_x_y_for_national_weather_serv...,Step 1: {'name': 'current_weather_data_of_a_lo...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,5074,AnswerStatus.Solved,passed,Is solved: The answer provides the current wea...,True
59,I'm planning a summer party and I want to serv...,TaskStatus.Solvable,['detailed_cocktail_recipe_by_id_for_the_cockt...,Step 1: {'name': 'list_of_cocktails_for_the_co...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,496,AnswerStatus.Solved,passed,Is solved: The answer provides a list of summe...,True
77,Can you find a Chuck Norris joke that mentions...,TaskStatus.Solvable,"['jokes_search_for_chuck_norris', 'jokes_rando...",Step 1: {'name': 'jokes_search_for_chuck_norri...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6446,AnswerStatus.Solved,passed,Is solved: All the tools in the chain were suc...,True

In [18]:
data_self_correct = pd.read_csv('/data4/polyakov/instruction_tuning/ToolBench/data/answer/test_toollama_2_G3_inst_test_gpt_4_explanations_converted/toollama_2/G3_instruction_toollama_2.csv',
                   sep='\t')

In [27]:
data_self_correct_solved = data_self_correct[data_self_correct['is_solved'] == 'AnswerStatus.Solved']
print(data_self_correct_solved.shape)
data_self_correct_solved

(7, 11)

,query,solvable,available_tools,model_intermediate_steps,model_final_step,model,query_id,is_solved,pass_rate_label,reason,not_hallucinate
1,I'm organizing a charity event to raise funds ...,TaskStatus.Solvable,"['v1_jokes_for_jokes_by_api_ninjas', 'quote_fo...","Step 1: {'name': 'quote_for_quotes', 'argument...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,9928,AnswerStatus.Solved,passed,Is solved: The 'tool' node in the chain contai...,True
12,My friend is planning a destination wedding in...,TaskStatus.Solvable,"['get_5_day_forecast_for_weather', 'severe_wea...",Step 1: {'name': 'weather_forecast_data_for_vi...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4758,AnswerStatus.Solved,passed,Is solved: The answer provides the requested 5...,True
32,I'm planning a hiking trip in the mountains an...,TaskStatus.Solvable,['get_1_hour_minutely_forecast_nowcast_for_wea...,Step 1: {'name': 'get_5_day_forecast_for_weath...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6940,AnswerStatus.Solved,passed,Is solved: The answer provides a detailed 5-da...,True
34,I need to plan a beach party for my company. C...,TaskStatus.Solvable,['current_weather_data_of_a_location_for_weath...,Step 1: {'name': 'get_5_day_forecast_for_weath...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4819,AnswerStatus.Solved,passed,Is solved: The answer provides the 5-day weath...,True
38,I'm a software developer working on a project ...,TaskStatus.Solvable,['proxies_example_json_for_proxy_spider_proxie...,"Step 1: {'name': 'ip2proxy_api_for_ip2proxy', ...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6773,AnswerStatus.Solved,passed,Is solved: The answer provides all the request...,True
43,My family and I are planning a ski trip to Asp...,TaskStatus.Solvable,['gridpoints_wfo_x_y_for_national_weather_serv...,Step 1: {'name': 'current_weather_data_of_a_lo...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,5074,AnswerStatus.Solved,passed,Is solved: The answer provides the current wea...,True
51,I'm planning a surprise visit to my grandparen...,TaskStatus.Solvable,"['v1_jokes_for_jokes_by_api_ninjas', 'get_by_i...","Step 1: {'name': 'random_for_manatee_jokes', '...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,828,AnswerStatus.Solved,passed,Is solved: The answer provides a detailed resp...,True

In [19]:
data_self_correct_passed = data_self_correct[data_self_correct['pass_rate_label'] == 'passed']

In [24]:
data_self_correct_passed[~data_self_correct_passed['query_id'].isin(data_passed['query_id'])]

,query,solvable,available_tools,model_intermediate_steps,model_final_step,model,query_id,is_solved,pass_rate_label,reason,not_hallucinate
0,I'm organizing a family gathering and I want t...,TaskStatus.Solvable,"['v1_memes_for_programming_memes_images', 'get...","Step 1: {'name': 'random_for_daddyjokes', 'arg...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,7014,AnswerStatus.Unsolved,passed,Is solved: The answer provides the requested d...,True
1,I'm organizing a charity event to raise funds ...,TaskStatus.Solvable,"['v1_jokes_for_jokes_by_api_ninjas', 'quote_fo...","Step 1: {'name': 'quote_for_quotes', 'argument...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,9928,AnswerStatus.Solved,passed,Is solved: The 'tool' node in the chain contai...,True
4,I'm organizing a family gathering and I want t...,TaskStatus.Unsure,"['search_for_soundcloud', 'playlist_info_for_s...","Step 1: {'name': 'search_for_deezer', 'argumen...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6144,AnswerStatus.Unsolved,passed,Is solved: The answer is a positive response t...,True
5,I'm preparing a funny presentation for my clas...,TaskStatus.Solvable,"['get_random_joke_for_world_of_jokes', 'get_jo...",Step 1: {'name': 'v1_jokes_for_jokes_by_api_ni...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,605,AnswerStatus.Unsolved,passed,Is solved: The answer is a positive response a...,True
8,I'm a music enthusiast and I want to explore t...,TaskStatus.Unsolvable,"['view_song_copy_for_view_song', 'view_song_fo...",Step 1: {'name': 'adult_pop_songs_for_billboar...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,9052,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
19,I'm organizing a Hearthstone tournament and I ...,TaskStatus.Unsolvable,"['card_backs_for_hearthstone', 'cards_by_type_...","Step 1: {'name': 'card_backs_for_hearthstone',...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,3545,AnswerStatus.Unsolved,passed,Is solved: The answer is a sorry message and n...,True
21,I want to surprise my friends with some funny ...,TaskStatus.Solvable,"['jokes_random_for_chuck_norris', 'jokes_categ...",Step 1: {'name': 'get_random_joke_for_world_of...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4575,AnswerStatus.Unsure,passed,Is solved: The answer contains a random joke f...,True
30,I'm planning a weekend getaway with my family ...,TaskStatus.Solvable,"['alerts_active_for_national_weather_service',...",Step 1: {'name': 'current_weather_data_of_a_lo...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,7589,AnswerStatus.Unsure,passed,Is solved: I am unable to verify the authentic...,True
31,I want to create a relaxing playlist for my yo...,TaskStatus.Unsolvable,"['song_download_for_soundcloud', 'search_for_s...","Step 1: {'name': 'search_for_soundcloud', 'arg...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,8455,AnswerStatus.Unsolved,passed,Is solved: The answer is a positive response t...,True
34,I need to plan a beach party for my company. C...,TaskStatus.Solvable,['current_weather_data_of_a_location_for_weath...,Step 1: {'name': 'get_5_day_forecast_for_weath...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4819,AnswerStatus.Solved,passed,Is solved: The answer provides the 5-day weath...,True
51,I'm planning a surprise visit to my grandparen...,TaskStatus.Solvable,"['v1_jokes_for_jokes_by_api_ninjas', 'get_by_i...","Step 1: {'name': 'random_for_manatee_jokes', '...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,828,AnswerStatus.Solved,passed,Is solved: The answer provides a detailed resp...,True
55,I'm planning a team-building activity for my c...,TaskStatus.Unsolvable,"['post_search_for_socialgrep', 'comment_search...","Step 1: {'name': 'post_search_for_socialgrep',...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,4048,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
61,I'm planning a family gathering and we need so...,TaskStatus.Unsolvable,"['track_for_deezer', 'artist_for_deezer', 'com...",Step 1: {'name': 'top_artists_duo_group_for_bi...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6549,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
68,I'm a cryptocurrency trader and I need to know...,TaskStatus.Unsolvable,"['get_global_stats_for_coinranking', 'get_refe...","Step 1: {'name': 'exchanges_for_tardis_dev', '...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,9998,AnswerStatus.Unsure,passed,Is solved: The details of the Binance exchange...,True
71,I'm organizing a health seminar and I need a c...,TaskStatus.Unsolvable,"['vac_for_getguidelines', 'all_for_getguidelin...","Step 1: {'name': 'all_for_getguidelines', 'arg...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,7721,AnswerStatus.Unsolved,passed,Is solved: The answer does not provide a compr...,True
87,I'm hosting a karaoke night and I need a list ...,TaskStatus.Unsolvable,['songs_list_artist_top_tracks_deprecated_for_...,Step 1: {'name': 'songs_list_artist_top_tracks...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,6522,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
88,My company is planning to invest in the stock ...,TaskStatus.Unsure,['type_risk_get_risk_return_analysis_for_morni...,Step 1: {'name': 'type_risk_get_risk_return_an...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,66,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
96,I am organizing a music-themed party for my fr...,TaskStatus.Unsolvable,"['get_artists_for_spotify', 'get_radio_playlis...","Step 1: {'name': 'search_for_deezer', 'argumen...","Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,9946,AnswerStatus.Unsolved,passed,Is solved: Empty final answer!\nTask solvable:...,True
97,I am a sports blogger and I'm always looking f...,TaskStatus.Unsure,"['v4_sports_sport_odds_for_live_sports_odds', ...",Step 1: {'name': 'v4_sports_for_live_sports_od...,"Final step: {'name': 'Finish', 'arguments': '{...",toollama_2,710,AnswerStatus.Unsolved,passed,Is solved: The answer is a sorry message and d...,True

In [9]:
import json

In [11]:
data = json.load(open('/data4/polyakov/instruction_tuning/ToolBench/data/toolbench_new_1311/test_data_merged/G1_inst.json'))

In [14]:
g1_inst_first_10 = data[:10]

In [17]:
json.dump(g1_inst_first_10, open('/data4/polyakov/instruction_tuning/ToolBench/data/toolbench_new_1311/test_data_merged/G1_inst_first_10.json', 'w'),
          ensure_ascii=False)